/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskId = IDL.Text;
export const Task = IDL.Record({
  'reward' : IDL.Float64,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const WithdrawalRequest = IDL.Record({ 'amount' : IDL.Float64 });
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'tasksCompleted' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([TaskId], [], []),
  'createTask' : IDL.Func([TaskId, IDL.Text, IDL.Text, IDL.Float64], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllTasksByReward' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, WithdrawalRequest))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTask' : IDL.Func([TaskId], [Task], ['query']),
  'getUserBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestWithdrawal' : IDL.Func([IDL.Float64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedChunkTasks' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskId = IDL.Text;
  const Task = IDL.Record({
    'reward' : IDL.Float64,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const WithdrawalRequest = IDL.Record({ 'amount' : IDL.Float64 });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'tasksCompleted' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([TaskId], [], []),
    'createTask' : IDL.Func([TaskId, IDL.Text, IDL.Text, IDL.Float64], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllTasksByReward' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, WithdrawalRequest))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTask' : IDL.Func([TaskId], [Task], ['query']),
    'getUserBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestWithdrawal' : IDL.Func([IDL.Float64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedChunkTasks' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };